#!/usr/bin/env bash

col() {
  local row name type key
  for row in "$@"; do
    IFS='|' read -r name type key <<< "$row"
    case "$key" in
      PK)  printf '    %s: %s {constraint: primary_key}\n' "$name" "$type" ;;
      FK)  printf '    %s: %s {constraint: foreign_key}\n' "$name" "$type" ;;
      UNQ) printf '    %s: %s {constraint: unique}\n'      "$name" "$type" ;;
      *)   printf '    %s: %s\n'                           "$name" "$type" ;;
    esac
  done
}

table() {
  local id="$1" group="$2"; shift 2
  printf '%s: {\n  shape: sql_table\n  class: %s\n' "$id" "$group"
  col "$@" | sed 's/^  //'
  printf '}\n'
}

enum() {
  local id="$1"; shift
  printf '  %s: {\n    shape: sql_table\n    style.fill: "#dce0e8"\n    style.stroke: "#ffffff"\n    style.font-color: "#4c4f69"\n' "$id"
  printf '    %s: ""\n' "$@"
  printf '  }\n'
}

group() {
  printf '  %s: {\n    style: {\n      fill: "%s"\n      stroke: "#ffffff"\n      font-color: "#4c4f69"\n      font-size: 18\n      stroke-width: 0\n    }\n  }\n' "$1" "$2"
}

cat <<EOF
# Spektra database diagram. Generated by docs/figures/gen-db-d2.sh, rendered with
# docs/figures/build.sh. Header colour is the table's group, matching the subsystem
# colours in arkitektur.d2.
#
# The uniform audit columns (created_at, updated_at) are left out to keep the
# figure readable. The migrations have them.

vars: {
  d2-config: {
    layout-engine: elk
    pad: 20
    theme-overrides: {
      B1: "#4c4f69"
      B2: "#4c4f69"
      AA2: "#6c6f85"
    }
  }
}

direction: down

classes: {
$(group adgang '#c3e1b8')
$(group flaade '#bfd1fb')
$(group maaledata '#dcc3fa')
$(group haendelser '#ffcfb2')
}

forklaring: "" {
  grid-rows: 1
  horizontal-gap: 24
  style: {fill: transparent; stroke: transparent}
tabelgrupper: "Tabelgrupper" {
  grid-columns: 1
  grid-gap: 8
  style: {fill: "#ffffff"; stroke: "#9ca0b0"; font-color: "#4c4f69"; font-size: 19; bold: false}
  adgang: "Adgang" {class: adgang; width: 150; height: 40; style.bold: false; style.font-size: 17}
  flaade: "Flåde" {class: flaade; width: 150; height: 40; style.bold: false; style.font-size: 17}
  maaledata: "Måledata" {class: maaledata; width: 150; height: 40; style.bold: false; style.font-size: 17}
  haendelser: "Hændelser" {class: haendelser; width: 150; height: 40; style.bold: false; style.font-size: 17}
}
enumtyper: "Enumtyper" {
  style: {fill: "#ffffff"; stroke: "#9ca0b0"; font-color: "#4c4f69"; font-size: 19; bold: false}
$(enum modulation fm dab)
$(enum metric signal_strength signal_to_noise carrier_offset demod_error_rate spectrum_occupancy)
$(enum rollup_resolution hourly daily weekly)
$(enum alarm_state open acknowledged under_verification closed)
$(enum work_order_status assigned completed)
}
}

$(table roles adgang "id|bigserial|PK" "name|varchar(32)|UNQ" "description|text|")
$(table users adgang "id|bigserial|PK" "email|varchar(320)|UNQ" "password_hash|text|" "full_name|varchar(100)|" "role_id|bigint|FK" "deactivated|boolean|")
$(table sessions adgang "id|bigserial|PK" "token|varchar(255)|UNQ" "user_id|bigint|FK" "expires_at|timestamp|" "last_used_at|timestamp|")

$(table nodes flaade "id|bigserial|PK" "external_identity|varchar(64)|UNQ" "name|varchar(100)|" "latitude|float8|" "longitude|float8|" "hardware|jsonb|" "capabilities|jsonb|" "suspended|boolean|" "report_interval_seconds|int|" "channel_plan_version|bigint|" "owner_id|bigint|FK" "last_seen_at|timestamp|")
$(table node_credentials flaade "id|bigserial|PK" "node_id|bigint|FK" "token|varchar(255)|UNQ" "expires_at|timestamp|" "revoked_at|timestamp|")
$(table channels flaade "id|bigserial|PK" "name|varchar(100)|" "frequency_hz|bigint|UNQ" "modulation|modulation (enum)|UNQ")
$(table node_channels flaade "id|bigserial|PK" "node_id|bigint|FK" "channel_id|bigint|FK" "bandwidth_hz|integer|")

$(table measurements maaledata "id|bigserial|PK" "window_start|timestamp|PK" "node_id|bigint|FK" "channel_id|bigint|FK" "metric|metric (enum)|" "window_end|timestamp|" "min|float8|" "max|float8|" "mean|float8|" "median|float8|" "stddev|float8|" "p95|float8|" "sample_count|bigint|")
$(table rollups maaledata "id|bigserial|PK" "node_id|bigint|FK" "channel_id|bigint|FK" "metric|metric (enum)|" "resolution|rollup_resolution (enum)|" "bucket_start|timestamp|" "bucket_end|timestamp|" "min|float8|" "max|float8|" "mean|float8|" "median|float8|" "stddev|float8|" "sample_count|bigint|")
$(table node_health maaledata "id|bigserial|PK" "node_id|bigint|FK" "measured_at|timestamp|UNQ" "uptime_seconds|float8|" "load_1m|float8|" "load_5m|float8|" "load_15m|float8|" "cpu_temperature_celsius|float8|" "clock_offset_seconds|float8|")

$(table alarms haendelser "id|bigserial|PK" "node_id|bigint|FK" "channel_id|bigint|FK" "metric|metric (enum)|" "state|alarm_state (enum)|" "explanation|jsonb|" "raised_at|timestamp|" "closed_at|timestamp|")
$(table alarm_events haendelser "id|bigserial|PK" "alarm_id|bigint|FK" "from_state|alarm_state (enum)|" "to_state|alarm_state (enum)|" "changed_by_user_id|bigint|FK" "reason|text|")
$(table work_orders haendelser "id|bigserial|PK" "alarm_id|bigint|FK" "technician_user_id|bigint|FK" "station_name|text|" "status|work_order_status (enum)|" "fault_present|boolean|" "cause|text|" "action_taken|text|" "completed_at|timestamp|")

forklaring.tabelgrupper -> alarm_events: {style.opacity: 0}
forklaring.enumtyper -> work_orders: {style.opacity: 0}
users.role_id -> roles.id
sessions.user_id -> users.id
nodes.owner_id -> users.id
node_credentials.node_id -> nodes.id
node_channels.node_id -> nodes.id
node_channels.channel_id -> channels.id
measurements.node_id -> nodes.id
measurements.channel_id -> channels.id
rollups.node_id -> nodes.id
rollups.channel_id -> channels.id
node_health.node_id -> nodes.id
alarms.node_id -> nodes.id
alarms.channel_id -> channels.id
alarm_events.alarm_id -> alarms.id
alarm_events.changed_by_user_id -> users.id
work_orders.alarm_id -> alarms.id
work_orders.technician_user_id -> users.id

(** -> **)[*].style.stroke: "#6c6f85"
(** -> **)[*].style.stroke-width: 2
EOF
