use std::ops::RangeInclusive;

#[expect(
    clippy::allow_attributes,
    clippy::as_conversions,
    clippy::clone_on_ref_ptr,
    clippy::default_trait_access,
    clippy::derive_partial_eq_without_eq,
    clippy::doc_markdown,
    clippy::must_use_candidate,
    clippy::missing_const_for_fn,
    clippy::missing_errors_doc,
    clippy::too_many_lines,
    reason = "generated by tonic-prost-build from proto/v1, not hand-written"
)]
pub mod v1 {
    tonic::include_proto!("spektra.v1");
}

pub const PROTOCOL_VERSION: &str = "1";

#[must_use]
pub const fn metric_range(metric: v1::Metric) -> Option<RangeInclusive<f64>> {
    match metric {
        v1::Metric::SignalStrength => Some(-150.0..=0.0),
        v1::Metric::SignalToNoise => Some(0.0..=80.0),
        v1::Metric::CarrierOffset => Some(-200_000.0..=200_000.0),
        v1::Metric::DemodErrorRate | v1::Metric::SpectrumOccupancy => Some(0.0..=1.0),
        v1::Metric::Unspecified => None,
    }
}
